version: 2.1

jobs:

  deploy_development_environment:
    machine:
      image: ubuntu-2204:2022.10.1
    steps:
      - checkout
      - run:
          name: Set the environment variables
          command: python crewtech_scripts/set_env_vars.py \
                   --env=development \
                   --token=$CIRCLE_TOKEN \
                   --owner=$OWNER_ID
      - run:
          name: Push the code
          command: rsync -r crewtech_api crewtech_scripts/run_development.sh root@$SERVER_IP:/root/crewtech
      - run:
          name: Run the script
          command: ssh root@$SERVER_IP "sh crewtech/run_development.sh"

  deploy_staging_environment:
    machine:
      image: ubuntu-2204:2022.10.1
    steps:
      - checkout
      - run:
          name: Set the environment variables
          command: python crewtech_scripts/set_env_vars.py \
                   --env=staging \
                   --token=$CIRCLE_TOKEN \
                   --owner=$OWNER_ID
      - run:
          name: Push the code
          command: rsync -r crewtech_api crewtech_scripts/run_staging.sh root@$SERVER_IP:/root/crewtech
      - run:
          name: Run the script
          command: ssh root@$SERVER_IP "sh crewtech/run_staging.sh"

  deploy_production_environment:
    machine:
      image: ubuntu-2204:2022.10.1
    steps:
      - checkout
      - run:
          name: Set the environment variables
          command: python crewtech_scripts/set_env_vars.py \
                   --env=production \
                   --token=$CIRCLE_TOKEN \
                   --owner=$OWNER_ID
      - run:
          name: Push the code
          command: rsync -r crewtech_api crewtech_scripts/run_production.sh root@$SERVER_IP:/root/crewtech
      - run:
          name: Run the script
          command: ssh root@$SERVER_IP "sh crewtech/run_production.sh"

workflows:
  deploy:
    jobs:
      - deploy_development_environment:
          context:
            - crewtech_common_context
            - crewtech_development_context
          filters:
            branches:
              only: main

      - deploy_staging_environment:
          context:
            - crewtech_common_context
            - crewtech_staging_context
          requires:
            - deploy_development_environment
          filters:
            branches:
              only: main

      - deploy_production_environment:
          context:
            - crewtech_common_context
            - crewtech_production_context
          requires:
            - deploy_staging_environment
          filters:
            branches:
              only: main
