version: '3.9'

services:

  django:
    image: crewtech_staging
    container_name: crewtech_staging_django
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../.env/.env.staging
    ports:
      - "80:8000"
    volumes:
      - ../:/crewtech_api
    command: sh -c "chmod +x /crewtech_api/entrypoint.sh && sh /crewtech_api/entrypoint.sh"

  celery:
    image: crewtech_staging
    container_name: crewtech_staging_celery
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    command: /opt/venv/bin/celery -A src worker -l INFO
    env_file:
      - ../.env/.env.staging
    volumes:
      - ../:/crewtech_api
    depends_on:
      - django

volumes:
  redis_data:
