version: '3.9'

services:

  django:
    image: creditor_base
    container_name: creditor_base_django
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../.env/.env.base
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ../:/backend
    command: sh -c "chmod +x ./entrypoint.sh && sh ./entrypoint.sh"

  postgres:
    image: postgres:13-alpine
    container_name: creditor_base_postgres
    env_file:
      - ../.env/.env.base
    ports:
      - "5432:5432"
    volumes:
      - ../../.volumes/postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: creditor_base_rabbitmq
    env_file:
      - ../.env/.env.base
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ../../.volumes/rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    container_name: creditor_base_redis
    ports:
      - "6379:6379"
    volumes:
      - ../../.volumes/redis_data:/data

  celery:
    image: creditor_base
    container_name: creditor_base_celery
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    command: /opt/venv/bin/celery -A src worker -l INFO
    env_file:
      - ../.env/.env.base
    volumes:
      - ../:/backend
    depends_on:
      - rabbitmq
      - redis
      - django

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
