version: '3.9'

services:

  django:
    image: crewtech_production
    container_name: crewtech_production_django
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        environment: production
    restart: always
    env_file:
      - ../.env/.env.production
    ports:
      - "80:8000"
    volumes:
      - ../:/backend
    command: sh -c "chmod +x ./entrypoint.sh && sh ./entrypoint.sh"

  celery:
    image: crewtech_production
    container_name: crewtech_production_celery
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        environment: production
    restart: always
    command: /opt/venv/bin/celery -A src worker -l INFO
    env_file:
      - ../.env/.env.production
    volumes:
      - ../:/backend
    depends_on:
      - django
